version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    user: "999:999"
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_PASSWORD: 0traClave
      MARIADB_DATABASE: PEPS
    # userns_mode: keep
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - prueba

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 9093:80
    depends_on:
      - mariadb
    networks:
      - prueba

  python:
    build: .
    container_name: python
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: PEPS
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    depends_on:
        - mariadb
    networks:
      - prueba
  apache:
    build: ./apache
    container_name: apache
    volumes:
      - ./apache/web:/usr/local/apache2/htdocs/
    ports:
      - "7777:80"
    networks:
      - prueba
    depends_on: 
      - python 

networks:
  prueba:
    driver: bridge